const ALERT = "ALERT";
const REFETCH_CHAT = "REFETCH_CHAT";
const NEW_ATTACHEMENT = "NEW_ATTACHEMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE = "NEW_MESSAGE";

export { ALERT, REFETCH_CHAT, NEW_ATTACHEMENT, NEW_MESSAGE_ALERT, NEW_MESSAGE };
